### ISSUE TITLE
DNS01 method?

### ISSUE THREAD

**Issue by pentago** [ahmetb/gke-letsencrypt#10]
Great guide Ahmet, any chance of providing additional instructions or modifying current ones to use DNS method? Seems a bit less error-prone and more manageable in a long run.

Thanks in advance!

**Comment by ahmetb** [comment]
Please read cert-manager documentation for that.

**Comment by pentago** [comment]
I did several times actually, for some reason it didn't work with their example manifests. Your http01 works just fine but it'd be awesome to have dns01 method working as well.

**Comment by ahmetb** [comment]
I recommend opening an issue there or getting help in #cert-manager channel on slack.k8s.io.

**Comment by pentago** [comment]
Sure, thanks!
