### ISSUE TITLE
GKE with Cloud Endpoints (Help)

### ISSUE THREAD

**Issue by samsends** [ahmetb/gke-letsencrypt#14]
First off, thank you for such a great guide. I am stuck with one aspect. I have a letsencrypt-prod cluster BUT I am using cloud endpoints (not an ingress controller). How should I point letsencrypt to the Google Cloud Load Balancer?

# Service / Deployment
```golang
# kubectl create -f config.yaml
apiVersion: v1
kind: Service
metadata:
  name: tensortask-api
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http1
  - port: 81
    targetPort: 9001
    protocol: TCP
    name: http2
  selector:
    app: tensortask-api
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensortask-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tensortask-api
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port", "9000",  # for HTTP 1.1
          "--http2_port", "9001",  # for gRPC
          "-a", "grpc://127.0.0.1:8000",
          "-s", "api.tensortask.com",
          "--rollout_strategy", "managed",
          ]
        ports:
          - containerPort: 9000
          - containerPort: 9001

      - name: go-backend
        image: gcr.io/tensortask/server:latest
        ports:
          - containerPort: 8000

``` 
# Certificate
```golang

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tensortask-com-tls
  namespace: default
spec:
  secretName: tensortask-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.tensortask.com
  dnsNames:
  - api.tensortask.com
  acme:
    config:
    - http01:
        ingress: ??????????
      domains:
      - api.tensortask.com

```

**Comment by ahmetb** [comment]
Have you looked at https://cloud.google.com/endpoints/docs/openapi/enabling-ssl ?

**Comment by samsends** [comment]
Yes, but I would like to use Let's Encrypt. The Let's Encrypt section just points to this repo.

**Comment by ahmetb** [comment]
Honestly, I'm not at all familiar with Endpoints.

It seems like ESP example in that link is using a `Service type:LoadBalancer` https://github.com/GoogleCloudPlatform/endpoints-samples/blob/master/k8s/esp_echo_gke.yaml cert-manager can't work with Service, it needs an Ingress to configure a TLS cert with.

If you convert that to `Service type:NodePort` and reference it in an `Ingress` that you'll create, it seems like it can work. 

See this doc on how to create an Ingress https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer backed by a `Service type:NodePort`.
