### ISSUE TITLE
Not working (secret is not created)

### ISSUE THREAD

**Issue by DPr00f** [ahmetb/gke-letsencrypt#16]
Followed the tutorial step by step.

Never got this
```
Type     Reason                Message
----     ------                -------
Warning  ErrorCheckCertificate Error checking existing TLS certificate: secret "www-dogs-com-tls" not found
Normal   PrepareCertificate    Preparing certificate with issuer
Normal   PresentChallenge      Presenting http-01 challenge for domain foo.kubernetes.tips
Normal   SelfCheck             Performing self-check for domain www.dogs.com
Normal   ObtainAuthorization   Obtained authorization for domain www.dogs.com
Normal   IssueCertificate      Issuing certificate...
Normal   CeritifcateIssued     Certificated issued successfully
Normal   RenewalScheduled      Certificate scheduled for renewal in 1438 hours
```

Got this instead

```
  Type    Reason          Age   From          Message
  ----    ------          ----  ----          -------
  Normal  CreateOrder     27m   cert-manager  Created new ACME order, attempting validation...
  Normal  DomainVerified  20m   cert-manager  Domain "ingresstest.myowndomain.com" verified with "http-01" validation
```

Which seems fine to me but the secret never got populated `kubectl get secrets`

And the domain never got the SSL certificate.

Will keep on investigating and will update the tutorial if I find a solution.

**Comment by gokulreddy07** [comment]
I too had same problem

**Comment by ahmetb** [comment]
Thanks for the report folks, I'll try to take a look if I can find time.

**Comment by hrdymchl** [comment]
I'm also facing a similar issue. Followed this step by step, and I see in the logs that the challenge was successful, but `kubectl describe -f certificate.yaml` returns and `kubectl get secrets` returns only the default service account token. I'm on version `1.10.6-gke.1`.
```
Events:
  Type    Reason       Age   From          Message
  ----    ------       ----  ----          -------
  Normal  CreateOrder  15m   cert-manager  Created new ACME order, attempting validation...
```

**Comment by ahmetb** [comment]
Ok I'm trying to reproduce this but failing at an entirely different stage.

```
$ kubectl describe -f certificate.yaml
...
  Type    Reason          Age   From          Message
  ----    ------          ----  ----          -------
  Normal  CreateOrder     28m   cert-manager  Created new ACME order, attempting validation...
  Normal  DomainVerified  22m   cert-manager  Domain "letest.alp.im" verified with "http-01" validation
```

It looks like my domain actually got the certificate at some point, although I don't see the Secret created, and it's not taking effect for sure.

**Comment by ahmetb** [comment]
This is weird. I did a `kubectl delete -f certificate.yaml`, changed to `letsencrypt-staging` and applied again: Got a secret just fine. 

Then deleted the secret, changed back to `letsencrypt-prod`, applied again, and got a prod certificate populated into Secret. Soo it seems like this is flaky.

Can someone try again like this?

**Comment by ahmetb** [comment]
To be clear, I was able to get a cert after doing `letsencrypt-prod` (failed) &rarr; `letsencrypt-staging` (worked) &rarr; `letsencrypt-prod` (worked).

**Comment by DPr00f** [comment]
:/ I don't know what happened. I could get a certificate using Issuer instead of ClusterIssuer...

This works for my purposes but don't understand why it's failing with eh cluster issuer.

**Comment by hrdymchl** [comment]
Yeah, seems flakey. I followed your steps @ahmetb but it's still failing with `http-01 self check failed for domain "my-domain.com".` I've seen a few posts on cert-manager that said the error cleared after a few days, so I'll just let it run.

**Comment by ahmetb** [comment]
I used ClusterIssuer and it worked fine. 🤷‍♂️ 

Definitely check out the logs for cert-manager pod in kube-system for the info. Also note that it's better to try things out with `letsencrypt-staging` as it has a higher rate limit than `-prod`.

**Comment by hrdymchl** [comment]
It's working now, but it feels unstable. I didn't get the message, `Normal   RenewalScheduled      Certificate scheduled for renewal in X hours`, but the cert was issued and I can serve traffic with the new cert, so maybe it needs some more time.

**Comment by ahmetb** [comment]
Trying a newer version of cert-manager chart might also help, but I doubt it. Hopefully this problem will be solved for good for GKE soon.

**Comment by hrdymchl** [comment]
Yeah, would love to see GKE handle this the way GAE handles it.

**Comment by bluemalkin** [comment]
I had the same issue.

I fixed it by upgrading cert-manager chart to v0.4.1

Hope this fixes it for you guys too.

**Comment by ahmetb** [comment]
If someone else can successfully get a cert by upgrading to v0.4.1, I'll open the chart version to that.

**Comment by seb-b** [comment]
Had the same problems described above.
I removed all the config, upgraded to 0.4.1 and reran all the steps and it gave me a working certificate

**Comment by ahmetb** [comment]
Bumping to 0.4.1.
