### ISSUE TITLE
[Question] Manage list of domains

### ISSUE THREAD

**Issue by jewome62** [ahmetb/gke-letsencrypt#24]
Hello,

I'm on project with multiple domains, and some domains can be added whenever.
I want to know, how factoring to have one list of domains ? ( And change list + deploy to have the good certificate)
Config values ? secret ? Helm variables ?
Make on certificate with all domains or a certificate by domain ?

Another question : we need the staging config ?

So thanks for this tutorial, that's very clear !

**Comment by ahmetb** [comment]
I recommend you join slack.k8s.io and ask this on #cert-manager room or https://github.com/jetstack/cert-manager/issues.

You don't need the staging config if you're not using it. It's unharmful.
