### ISSUE TITLE
Convert from staging to prod

### ISSUE THREAD

**Issue by MaxDiOrio** [ahmetb/gke-letsencrypt#27]
I was able to successfully request a cert using the letsencrypt-staging issuer.  Since it worked, I want to switch it to prod.  I updated the yaml and reapplied it.  If I describe it, I see that it is using the new yaml with letsencrypt-prod.

But how/when does it go out and update the cert to to the prod version?

Thanks!

**Comment by MaxDiOrio** [comment]
I deleted the yaml, deleted the staging cert, and re-created the yaml.

**Comment by ahmetb** [comment]
You should ask this on cert-manager repository.
