### ISSUE TITLE
Tracking pixels

### ISSUE THREAD

**Issue by abevoelker** [ahmetb/gke-letsencrypt#29]
What's the deal with the tracking pixels in the markdown files? To my knowledge that's not legal in many jurisdictions without an accompanying privacy policy, which I'm not seeing. Besides, is it even effective [given GitHub's Camo image proxy](https://github.com/igrigorik/ga-beacon/commit/6acd8627bb7be36f24f5516e9873c92719a50e55)?

GitHub [already has a traffic page](https://github.com/ahmetb/gke-letsencrypt/graphs/traffic) in case you weren't aware, which is obviously covered by their privacy policy.

**Comment by ahmetb** [comment]
Yeah as you said it goes through github proxy, so I only get anonymized data, but I am not even sure if that's 1:1 mapping to the visitor count. It helps me understand the trends like whether usage is growing or not.

**Comment by abevoelker** [comment]
Okay
