### ISSUE TITLE
http->https redirect?

### ISSUE THREAD

**Issue by sriney-staked** [ahmetb/gke-letsencrypt#32]
Not an issue per se, but it doesn't appear that the annotation for the regular (GCE)/ingress controller works in this case (using:  kubernetes.io/ingress.allow-http: "false").

Do I need to upgrade to the Nginx controller?  Can that be done in the step before requesting the cert such that the automation to update the ingress manifest will work?

https://github.com/kubernetes/ingress-nginx/

**Comment by ahmetb** [comment]
Haven't tried with ingress-nginx myself, but just know that LetsEncrypt doesn't require a certificate while validating the requests.

so if you

1. set up http->https redirect
2. request a cert

then LE challenge request will go to https:// (which has no valid cert) but LE doesn't care about the bad/no cert situation.

I'd google "nginx-ingress" LetsEncrypt and/or ask this on "cert-manager" repo.
