### ISSUE TITLE
Cert Renewal

### ISSUE THREAD

**Issue by dannydeezy** [ahmetb/gke-letsencrypt#34]
Hi - I'm wondering what is the recommended way to renew certs? The tutorial was great and worked, but 2 months later (now) I got a notification that my certificate will expire in a month. How do you recommend I renew the certificate? I'd prefer not to re-route my domain name to the cert solver again, as this will block access to my app and interrupt my customers.

**Comment by dannydeezy** [comment]
I see in the docs it says cert-manager will auto-renew. unfortunately i deleted it entirely from my cluster after I originally got the cert. thoughts on how to move forward? do i need the static IP and ingress up for cert-manager to renew the certs?

**Comment by ahmetb** [comment]
cert-manager renews certs. Please go read their documentation.
