### ISSUE TITLE
Error with `helm init --service-account tiller`

### ISSUE THREAD

**Issue by chadsaun** [ahmetb/gke-letsencrypt#38]
When I run `helm init --service-account tiller` I get the following:

```
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
```

If I continue to try to install the cert-manager then I get this issue #25 

I already installed Tiller because it was the next step right after installing Helm on the page that you linked to in the instructions.

**Comment by ahmetb** [comment]
> When I run `helm init --service-account tiller` I get the following:

I can't help you if you already have Tiller installed. You should probably learn how to use Helm in this case.

> If I continue to try to install the cert-manager then I get this issue #25

I recommend you ask this on `cert-manager` repo. I think there's no clear bugs as I see them in #25, all the commands listed there are already in the tutorial. If you can figure why instructions in #25 works, please make a PR.

**Comment by chadsaun** [comment]
So I resolved this issue by simply running `helm init --service-account tiller --upgrade`

Then I was also able to install the cert-manager successfully.
