### ISSUE TITLE
Give more document space to the DNS setup step

### ISSUE THREAD

**Issue by corydodt** [ahmetb/gke-letsencrypt#4]
LOVING this tutorial so far, but I noticed one issue on this page:

https://github.com/ahmetb/gke-letsencrypt/blob/master/40-deploy-an-app.md

> After it works, update your domain name records (at your domain registrar or DNS provider) with this IP address.

This is a critical instruction, but you presented it as a single line with no highlight or bullet or anything. It's easy to gloss over instructions like this. I understand not wanting to link to every conceivable DNS update mechanism, but can you just make this take up more space on the page? Even something as simple as adding a bullet or some bold would help it stand out. (Notably, the other instructions on the same page don't need anything extra, because they're followed by code blocks.)

Great job on this tutorial in general, I was really struggling with cert-manager until I found it!

**Comment by ahmetb** [comment]
I assume people know how to point their DNS records to an IP address.

I am not sure how can I improve this part, because every single Domain Registrar have different instructions. (Instructions on Godaddy won't be anywhere close to Google Domains, or name.com).

If you have any ideas on how to improve, please send a pull request.

**Comment by corydodt** [comment]
I'm not asking for more detailed instructions, just literally more space on the page so your eyes don't skip over this, and so you can find where, in the process, you expect this to happen. I'll send a PR.

**Comment by corydodt** [comment]
[PR #5 to add some bold](https://github.com/ahmetb/gke-letsencrypt/pull/5)
