### ISSUE TITLE
 `.well-known/acme-challenge/...` endpoint causes warning after certificate issued

### ISSUE THREAD

**Issue by heysailor** [ahmetb/gke-letsencrypt#9]
The endpoint `.well-known/acme-challenge/...` causes a warning, as the cert-manager service it points to is removed after the first certificate is issued.

Does the `.well-known/acme-challenge/...` endpoint need to stay configured, or can it be removed after the certificate is issued? Is it just used once for proof of ownership, or is needed for certificate renewal. 

Given it causes the warning, it would be good to clarify this in the walkthrough.

**Comment by ahmetb** [comment]
I think this is a question for the cert-manager project.
